import { useEffect, useRef, useState } from 'react'
import { DICE_SIDES, FACE_EFFECTS, MAX_POOL_DICE, combatSymbolFaces, defaultDicePool, dicePoolLabel, numericFaces, type DiceFace, type DicePool, type PoolDie } from '../lib/dice'
import type { LibraryEntry } from '../lib/object-library'
import { CLAW_DICE_COLORS, clawFaceArtwork, clawSymbolFaces, diceSkinColor, diceSkinFaceColor } from '../lib/dice-style'
import { loadDiceArtwork } from './dice-artwork'
import './dice-fields.css'

function DiceFaceChip({ face, color, index }: { face: DiceFace; color: string; index: number }) {
  const canvas = useRef<HTMLCanvasElement>(null), url = clawFaceArtwork(face), background = diceSkinFaceColor(color, face)
  const [failedUrl, setFailedUrl] = useState<string | null>(null)
  useEffect(() => {
    if (!url) return
    let active = true
    void loadDiceArtwork(url).then(art => {
      if (!active) return
      if (!art) { setFailedUrl(url); return }
      const ctx = canvas.current?.getContext('2d')
      if (!ctx) return
      ctx.clearRect(0, 0, 64, 64); ctx.fillStyle = background; ctx.fillRect(0, 0, 64, 64)
      ctx.drawImage(background.toLowerCase() === art.background ? art.source : art.foreground, 0, 0, 64, 64)
    })
    return () => { active = false }
  }, [url, background])
  return <b className="dice-face-chip" style={{ background }}>{url && failedUrl !== url ? <canvas ref={canvas} width={64} height={64} role="img" aria-label={face.label} /> : face.symbol || face.label || index + 1}<small>面{index + 1}</small></b>
}

export function DiceFacesEditor({ sides, faces, color = CLAW_DICE_COLORS.agent, onChange }: { sides: number; faces?: DiceFace[]; color?: string; onChange: (faces: DiceFace[] | undefined) => void }) {
  function patch(index: number, values: Partial<DiceFace>) { onChange((faces ?? numericFaces(sides)).map((f, i) => i === index ? { ...f, ...values } : f)) }
  return <div className="dice-face-editor"><div className="dice-field-row"><label>骰面类型<select value={faces ? 'custom' : 'numeric'} onChange={e => onChange(e.target.value === 'custom' ? numericFaces(sides) : undefined)}><option value="numeric">标准点数</option><option value="custom">自定义符号与数值</option></select></label>{sides === 6 && <><button type="button" onClick={() => onChange(combatSymbolFaces())}>使用战斗符号示例</button><button type="button" onClick={() => onChange(clawSymbolFaces('agent'))}>绿色探索骰</button><button type="button" onClick={() => onChange(clawSymbolFaces('planet'))}>棕色遗迹骰</button></>}</div>
    {faces && <><p className="dice-field-help">每行对应一个真实骰面，可重复图案来改变出现概率。投骰保存面号，结算读取该面的数值、成功数与效果。探索与遗迹预设使用原版图案，数值和效果可继续修改。</p><div className="dice-face-list">{faces.map((f, i) => <article className="dice-face-row" key={i}><DiceFaceChip face={f} color={color} index={i} /><label>符号<input aria-label={`第${i + 1}面符号`} value={f.symbol} maxLength={8} onChange={e => patch(i, { symbol: e.target.value })} /></label><label>名称<input aria-label={`第${i + 1}面名称`} value={f.label} maxLength={24} onChange={e => patch(i, { label: e.target.value })} /></label><label>数值<input aria-label={`第${i + 1}面数值`} type="number" min={0} max={10000} value={f.value} onChange={e => patch(i, { value: Math.max(0, Math.min(10000, Math.round(Number(e.target.value)))) })} /></label><label>成功数<input aria-label={`第${i + 1}面成功数`} type="number" min={0} max={10} value={f.successes} onChange={e => patch(i, { successes: Math.max(0, Math.min(10, Math.round(Number(e.target.value)))) })} /></label><label>颜色<input aria-label={`第${i + 1}面颜色`} type="color" value={diceSkinFaceColor(color, f)} onChange={e => patch(i, { color: e.target.value })} /></label><label>附加效果<select aria-label={`第${i + 1}面效果`} value={f.effect} onChange={e => patch(i, { effect: e.target.value as DiceFace['effect'] })}>{Object.entries(FACE_EFFECTS).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>{f.effect !== 'none' && f.effect !== 'stun' && <label>效果值<input aria-label={`第${i + 1}面效果值`} type="number" min={0} max={10000} value={f.amount} onChange={e => patch(i, { amount: Math.max(0, Math.min(10000, Math.round(Number(e.target.value)))) })} /></label>}</article>)}</div></>}
  </div>
}

export function DicePoolEditor({ pool: value, school = 0, entries = [], onChange }: { pool?: DicePool; school?: number; entries?: LibraryEntry[]; onChange: (pool: DicePool | undefined) => void }) {
  const pool = value ?? defaultDicePool(school), [notice, setNotice] = useState(''), count = pool.dice.reduce((n, d) => n + d.count, 0)
  function change(next: DicePool) { if (next.dice.reduce((n, d) => n + d.count, 0) > MAX_POOL_DICE) { setNotice('每次最多投20颗骰子，请先减少数量。'); return }; setNotice(''); onChange(next) }
  const patchDie = (index: number, v: Partial<PoolDie>) => change({ ...pool, dice: pool.dice.map((d, i) => i === index ? { ...d, ...v } : d) })
  const diceEntries = entries.filter(e => e.kind === 'dice')
  return <section className="dice-pool-editor"><h3>武功骰组 · {dicePoolLabel(pool)}</h3><p className="dice-field-help">同时掷出{count}颗实体骰子，全部落定后统一结算。每门武功可使用不同骰组；修改会随作品保存。</p><div className="dice-field-row"><button type="button" onClick={() => change({ ...pool, dice: [{ count: 3, sides: 6 }], mode: 'sum' })}>3d6 点数加成</button><button type="button" onClick={() => change({ ...pool, dice: [{ count: 2, sides: 20 }], mode: 'power' })}>2d20 威力浮动</button><button type="button" onClick={() => change({ ...pool, dice: [{ count: 2, sides: 6 }, { count: 1, sides: 20 }], mode: 'sum' })}>2d6 + d20</button><button type="button" onClick={() => change({ ...pool, dice: [{ count: 3, sides: 6, name: '战斗符号骰', faces: combatSymbolFaces() }], mode: 'success', multiplier: 5 })}>3颗符号骰</button><button type="button" onClick={() => onChange(undefined)}>恢复系别默认</button></div>
    <div className="dice-field-row"><label>结算方式<select value={pool.mode} onChange={e => change({ ...pool, mode: e.target.value as DicePool['mode'] })}><option value="power">威力浮动 · 保留现有强度</option><option value="sum">点数合计 · 追加伤害/治疗</option><option value="success">成功计数 · 0成功落空</option></select></label><label>固定修正<input type="number" min={-10000} max={10000} value={pool.modifier} onChange={e => change({ ...pool, modifier: Math.max(-10000, Math.min(10000, Math.round(Number(e.target.value)))) })} /></label>{pool.mode !== 'power' && <label>{pool.mode === 'sum' ? '每点追加威力' : '每成功追加威力'}<input type="number" min={1} max={100} value={pool.multiplier} onChange={e => change({ ...pool, multiplier: Math.max(1, Math.min(100, Math.round(Number(e.target.value)))) })} /></label>}{pool.mode === 'success' && <label>普通骰成功门槛<input type="number" min={1} max={20} value={pool.successTarget} onChange={e => change({ ...pool, successTarget: Math.max(1, Math.min(20, Math.round(Number(e.target.value)))) })} /></label>}</div>
    <p className="dice-field-help">{pool.mode === 'power' ? '各骰面按数值范围归一化，平均后转换为0.9–1.1威力浮动；固定修正作用于浮动值。' : pool.mode === 'sum' ? '现有属性与武功伤害 + 骰面数值合计 × 每点威力 + 固定修正；治疗和护盾也采用此加成。' : '普通骰达到门槛记1成功，自定义骰使用逐面成功数。0成功时招式落空；成功时在现有威力上追加成功数×每成功威力与修正。'}附加伤害作用于招式命中的敌人，恢复/护盾作用于施术者；0成功仍可触发自身恢复与护盾。</p>
    {pool.dice.map((d, i) => <details className="dice-pool-group" key={i} open={pool.dice.length === 1 ? true : undefined}><summary>{d.count}×{d.name || `d${d.sides}`} · {d.faces ? '自定义骰面' : '标准点数'}</summary><div className="dice-field-row"><label>数量<input aria-label={`第${i + 1}组骰子数量`} type="number" min={1} max={20} value={d.count} onChange={e => patchDie(i, { count: Math.max(1, Math.min(20, Math.round(Number(e.target.value)))) })} /></label><label>骰型<select aria-label={`第${i + 1}组骰型`} value={d.sides} onChange={e => patchDie(i, { sides: Number(e.target.value), faces: undefined })}>{DICE_SIDES.map(n => <option key={n} value={n}>d{n}</option>)}</select></label><label>名称<input value={d.name ?? ''} maxLength={48} placeholder={`d${d.sides}`} onChange={e => patchDie(i, { name: e.target.value })} /></label><label>底色<input type="color" value={diceSkinColor(d.color ?? [CLAW_DICE_COLORS.agent, CLAW_DICE_COLORS.planet][i % 2])} onChange={e => patchDie(i, { color: e.target.value })} /></label><button disabled={pool.dice.length === 1} type="button" onClick={() => change({ ...pool, dice: pool.dice.filter((_, n) => i !== n) })}>移除这一组</button></div><DiceFacesEditor sides={d.sides} color={d.color ?? [CLAW_DICE_COLORS.agent, CLAW_DICE_COLORS.planet][i % 2]} faces={d.faces} onChange={faces => patchDie(i, { faces })} /></details>)}
    <div className="dice-field-row"><button disabled={pool.dice.length >= 8 || count >= MAX_POOL_DICE} type="button" onClick={() => change({ ...pool, dice: [...pool.dice, { sides: 6, count: 1 }] })}>＋添加骰型</button>{!!diceEntries.length && <label>从物件库加入骰子<select value="" disabled={pool.dice.length >= 8 || count >= MAX_POOL_DICE} onChange={e => { const entry = diceEntries.find(d => d.id === e.target.value); if (entry) change({ ...pool, dice: [...pool.dice, { sides: entry.template.sides, count: 1, name: entry.name.slice(0, 48), color: entry.template.color, ...(entry.template.diceFaces ? { faces: structuredClone(entry.template.diceFaces) } : {}) }] }) }}><option value="">选择已保存骰子…</option>{diceEntries.map(e => <option key={e.id} value={e.id}>{e.name} · d{e.template.sides}{e.template.diceFaces ? ' · 自定义面' : ''}</option>)}</select></label>}</div>{notice && <p role="status">{notice}</p>}
  </section>
}
