import { tableBounds } from '../lib/table-surface'
import { useEffect, useState } from 'react'
import type { TableObject, TableSession, Vec3 } from '../lib/tabletop'
import { health, type Interaction } from '../lib/object-play'
import { attackRange, combatDistance, type CombatAction } from '../lib/combat'
import { movementRules } from '../lib/object-movement'
import './play-workbench.css'

interface ActionsProps { table: TableSession; object: TableObject; onAction: (id: string, action: Interaction, target?: string) => void; onHealth: (id: string, delta: number) => void; onMetadata: (id: string, values: TableObject['metadata']) => void; onDeal: (id: string, count: number, all: boolean) => void }
export function ObjectPlayActions({ table, object: o, onAction, onHealth, onMetadata, onDeal }: ActionsProps) {
  const [count, setCount] = useState(1); const behavior = o.metadata.behavior
  const locked = table.combat?.phase === 'rolling' || table.adventure?.progress.phase === 'rolling'
  return <fieldset className="pw-actions" disabled={locked}>
    {behavior === 'open' && <><button onClick={() => onAction(o.id, 'open')}>{o.metadata.opened ? '关闭' : '打开'}{o.name}</button>{o.metadata.lootName && <button disabled={!o.metadata.opened || Boolean(o.metadata.emptied)} onClick={() => onAction(o.id, 'loot')}>{o.metadata.emptied ? '宝箱已取空' : `取出${o.metadata.lootName}`}</button>}</>}
    {behavior === 'light' && <button onClick={() => onAction(o.id, 'light')}>{o.metadata.lit ? '熄灭' : '点燃'}{o.name}</button>}
    {behavior === 'switch' && <button onClick={() => onAction(o.id, 'switch')}>{o.metadata.activated ? '关闭机关' : '启动机关'}{o.metadata.linkTag ? ` · ${o.metadata.linkTag}` : ''}</button>}
    {o.kind === 'card' && o.metadata.item && !['inventory', 'hand'].includes(String(o.metadata.zone)) && <button onClick={() => onAction(o.id, 'collect')}>收进当前玩家背包</button>}
    {o.kind === 'deck' && <div className="pw-deal"><select aria-label="每人发牌数" value={count} onChange={e => setCount(Number(e.target.value))}>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>每人{n}张</option>)}</select><button disabled={o.locked} onClick={() => onDeal(o.id, count, false)}>发给当前玩家</button><button disabled={o.locked} onClick={() => onDeal(o.id, count, true)}>发给四位玩家</button></div>}
    {o.kind === 'figurine' && <><div className="pw-health"><span>生命 <b>{health(o, table).hp}/{health(o, table).max}</b></span><button onClick={() => onHealth(o.id, -1)}>−1</button><button onClick={() => onHealth(o.id, 1)}>+1</button></div><label>阵营<select aria-label="角色阵营" disabled={!!table.combat} value={String(o.metadata.team ?? '队伍')} onChange={e => onMetadata(o.id, { team: e.target.value })}>{['队伍', '敌方', '中立'].map(t => <option key={t}>{t}</option>)}</select></label><div className="pw-row"><button className={o.metadata.poisoned ? 'active' : ''} onClick={() => onMetadata(o.id, { poisoned: !o.metadata.poisoned })}>{o.metadata.poisoned ? '解除中毒' : '标记中毒'}</button><button className={o.metadata.guarded ? 'active' : ''} onClick={() => onMetadata(o.id, { guarded: !o.metadata.guarded })}>{o.metadata.guarded ? '解除防御' : '标记防御'}</button></div></>}
  </fieldset>
}

interface Props { table: TableSession; seat: string; moving: boolean; onMoveMode: () => void; onSelect: (id: string) => void; onInteract: ActionsProps['onAction']; onCombat: (action: CombatAction) => void; onAttack: (id: string) => void; exploreRequest?: number; scripted?: boolean }
export default function PlayWorkbench({ table, seat, moving, onMoveMode, onSelect, onInteract, onCombat, onAttack, exploreRequest = 0, scripted = false }: Props) {
  const figures = table.objects.filter(o => o.kind === 'figurine'); const [target, setTarget] = useState(''); const [recipient, setRecipient] = useState('玩家2')
  const [roster, setRoster] = useState<string[]>(() => figures.filter(o => !o.locked && health(o, table).hp > 0).map(o => o.id)); const [x, setX] = useState(0); const [z, setZ] = useState(0)
  useEffect(() => { if (recipient === seat) setRecipient(seat === "玩家1" ? "玩家2" : "玩家1") }, [seat, recipient])
  const [tab, setTab] = useState<'explore' | 'combat'>(() => table.combat ? 'combat' : 'explore')
  useEffect(() => { if (exploreRequest) setTab('explore') }, [exploreRequest])
  const bag = table.objects.filter(o => o.metadata.zone === 'inventory' && o.metadata.owner === seat)
  const s = table.combat, actor = s ? figures.find(o => o.id === s.order[s.turn]) : undefined
  const moveRule = actor && movementRules(actor)
  const moveDisabled = !s?.ap || moveRule?.mode === 'fixed' || Boolean(moveRule?.seat && moveRule.seat !== seat)
  useEffect(() => { if (s) setTab('combat') }, [Boolean(s)])
  const disabled = s?.phase === 'rolling' || s?.phase === 'complete'; const interactionLocked = s?.phase === 'rolling' || table.adventure?.progress.phase === 'rolling'
  const chooseMove = (position: Vec3) => onCombat({ type: 'move', position })
  return <div className="pw-workbench">
    <div className="pw-intro"><small>冒险行动</small><h3>探索与战斗</h3><p>与机关和道具互动，管理随身物品，带领角色完成遭遇。</p></div>
    <nav className="pw-tabs" aria-label="玩法分类"><button className={tab === 'explore' ? 'active' : ''} onClick={() => setTab('explore')}>探索与背包</button><button className={tab === 'combat' ? 'active' : ''} onClick={() => setTab('combat')}>战术战斗</button></nav>
    {table.name === '冒险工坊 · 交互沙盒' && tab === 'explore' && <details className="pw-lesson" open><summary>试玩指引 · 从这里开始</summary><ol><li>{table.objects.some(o => o.metadata.model === 'chest' && o.metadata.emptied) ? '✓' : '①'} 打开宝箱，再点“取物”。</li><li>{bag.length || table.logs.some(l => l.text.includes('收集了')) ? '✓' : '②'} 收集药剂，放进当前玩家背包。</li><li>{table.objects.some(o => o.metadata.model === 'lever' && o.metadata.activated) ? '✓' : '③'} 启动拉杆，观察门打开；点燃火把。</li><li>④ 切到“战术战斗”，开始遭遇。角色按顺序轮流行动，击倒全部敌方后提示胜利。受伤后可以使用药剂。</li></ol></details>}
    <section hidden={tab !== 'explore'}><h4>探索物件</h4><div className="pw-props">{table.objects.filter(o => o.metadata.behavior || o.metadata.item && !['inventory', 'hand'].includes(String(o.metadata.zone))).map(o => <div key={o.id}><button className="pw-name" onClick={() => onSelect(o.id)}>{o.name}</button>{o.metadata.behavior ? <button disabled={interactionLocked} onClick={() => onInteract(o.id, o.metadata.behavior as Interaction)}>{o.metadata.behavior === 'open' ? o.metadata.opened ? '关闭' : '打开' : o.metadata.behavior === 'light' ? o.metadata.lit ? '熄灭' : '点燃' : o.metadata.activated ? '关' : '启动'}</button> : <button disabled={interactionLocked} onClick={() => onInteract(o.id, 'collect')}>收集</button>}{o.metadata.lootName && <button disabled={!o.metadata.opened || Boolean(o.metadata.emptied) || interactionLocked} onClick={() => onInteract(o.id, 'loot')}>{o.metadata.emptied ? '已空' : '取物'}</button>}</div>)}</div></section>
    <section hidden={tab !== 'explore'}><h4>{seat}的背包 <em>{bag.length}件</em></h4><label>恢复目标<select aria-label="背包道具目标" value={target} onChange={e => setTarget(e.target.value)}><option value="">选择角色</option>{figures.map(o => <option key={o.id} value={o.id}>{o.name} · {health(o, table).hp}/{health(o, table).max}</option>)}</select></label><label>转交给<select aria-label="背包转交玩家" value={recipient} onChange={e => setRecipient(e.target.value)}>{['玩家1', '玩家2', '玩家3', '玩家4'].filter(o => o !== seat).map(o => <option key={o}>{o}</option>)}</select></label>{!bag.length && <p className="pw-muted">打开宝箱取物，再点击“收集”。</p>}{bag.map(item => <article className="pw-item" key={item.id}><b>{item.name}{item.metadata.equipped && <em>已装备</em>}</b><p>{item.description}</p><fieldset disabled={interactionLocked} className="pw-row">{item.metadata.consumable && <button onClick={() => onInteract(item.id, 'use', target)}>使用</button>}{item.metadata.equippable && <button onClick={() => onInteract(item.id, 'equip')}>{item.metadata.equipped ? '卸下' : '装备'}</button>}<button onClick={() => onInteract(item.id, 'drop')}>放回桌面</button><button onClick={() => onInteract(item.id, 'transfer', recipient)}>转交</button></fieldset></article>)}</section>
      <section hidden={tab !== 'combat'}><h4>战术遭遇</h4><details className="pw-rules"><summary>规则与操作说明</summary><p className="pw-muted">通用试玩规则：2行动点；移动4单位；近战1.8/远程6单位；d20+2≥10命中，伤害2；防御减伤1；恢复2生命消耗1专注；中毒在回合开始扣1生命。按角色顺序手动操作双方。</p></details>
      {!s ? <><div className="pw-roster">{figures.map(o => <label key={o.id}><input type="checkbox" checked={roster.includes(o.id)} onChange={e => setRoster(all => e.target.checked ? [...all, o.id] : all.filter(id => id !== o.id))} />{o.name}<small>{String(o.metadata.team ?? '队伍')}</small></label>)}</div><div className="pw-row"><button onClick={() => setRoster(figures.filter(o => !o.locked && health(o, table).hp > 0).map(o => o.id))}>选择全部角色</button><button onClick={() => onCombat({ type: 'start', ids: roster })}>开始战斗</button></div></> : <>
        <div className="pw-turn"><small>第{s.round}轮 · {String(actor?.metadata.team ?? '')}</small><h3>{s.phase === 'complete' ? s.message : actor?.name}</h3><b>{s.phase === 'complete' ? '遭遇已结束' : `${s.ap}/2 行动点 · ${actor?.metadata.focus ?? 0} 专注`}</b><p aria-live="polite">{s.message}</p></div>
        <ol className="pw-order">{s.order.map(id => { const o = figures.find(f => f.id === id)!; const h = health(o, table); return <li key={id} className={actor?.id === id ? 'active' : ''}><button onClick={() => onSelect(id)}>{o.name}</button><span>{h.hp}/{h.max}{o.metadata.guarded && ' ◇'}{o.metadata.poisoned && ' 毒'}</span></li> })}</ol>
        {actor && <fieldset disabled={disabled} className="pw-combat-controls"><div className="pw-row"><button onClick={() => onCombat({ type: 'defend' })} disabled={!s.ap}>防御 · 1AP</button><button onClick={() => onCombat({ type: 'recover' })} disabled={!s.ap}>恢复 · 1AP</button></div><label>移动目的地 · 最多{moveRule?.range}单位<div className="pw-row"><input aria-label="战斗移动 X" type="number" step={moveRule?.step} min={tableBounds(table).minX} max={tableBounds(table).maxX} value={x} onChange={e => setX(Number(e.target.value))} /><input aria-label="战斗移动 Z" type="number" step={moveRule?.step} min={tableBounds(table).minZ} max={tableBounds(table).maxZ} value={z} onChange={e => setZ(Number(e.target.value))} /><button disabled={moveDisabled} onClick={() => chooseMove([x, actor.position[1], z])}>移动</button></div></label><div className="pw-row">{([[-1, 0], [1, 0], [0, -1], [0, 1]] as const).map(([dx, dz], i) => <button key={i} disabled={moveDisabled} onClick={() => chooseMove([actor.position[0] + dx * (moveRule?.step ?? 1), actor.position[1], actor.position[2] + dz * (moveRule?.step ?? 1)])}>{['←', '→', '↑', '↓'][i]}</button>)}</div><button className="pw-primary" disabled={moveDisabled} onClick={onMoveMode}>{moving ? "取消地图移动" : "在地图上选择移动位置"}</button><h5>攻击目标 · 范围{attackRange(actor.metadata.model)}</h5>{s.order.map(id => figures.find(o => o.id === id)!).filter(o => o.metadata.team !== actor.metadata.team && health(o, table).hp > 0).map(o => <button className="pw-target" key={o.id} disabled={!s.ap || combatDistance(actor.position, o.position) > attackRange(actor.metadata.model) + .01} onClick={() => onAttack(o.id)}>{o.name}<small>距离{combatDistance(actor.position, o.position).toFixed(1)} · 掷d20</small></button>)}<button className="pw-primary" onClick={() => onCombat({ type: 'next' })}>结束当前角色回合</button></fieldset>}
        {s.phase === 'rolling' && <button onClick={() => onCombat({ type: 'cancel' })}>取消未完成攻击，保留行动点</button>}{!scripted && <button disabled={s.phase === 'rolling'} onClick={() => onCombat({ type: 'stop' })}>收起战斗，保留生命记录</button>}
      </>}
    </section>
  </div>
}
