import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import { Cards, Copy, Plus, UploadSimple, UserCircle } from '@phosphor-icons/react'
import type { AdventureDefinition } from '../lib/adventure-schema'
import { FIGURE_MODELS } from '../lib/play-kit'
import { createObject } from '../lib/tabletop'
import { instantiateLibraryEntry, uploadLibraryResource, type LibraryEntry } from '../lib/object-library'
import { configuredRpgCard, defaultRpgCard, withRpgCharacterCard, withRpgPartyCards, applyRpgCharacterPreset, refreshRpgCardValues, rpgAuthorCardPreview, type RpgCharacterGroup } from '../lib/rpg-character-cards'
import { characterRows, type TavernCard, type TavernField } from '../lib/tavern-presentation'
import { RPG_CARD_FIELDS, RPG_CHARACTER_PRESETS, RPG_SPECIALTIES } from '../lib/rpg-card-values'
import { dicePoolLabel } from '../lib/dice'
import { makeRpgCharacter, rpgSkillDice, SCHOOL_NAMES, type RpgMagic } from '../lib/rpg-rules'
import './rpg-character-studio.css'

const ObjectPreview = lazy(() => import('./ObjectPreview'))
interface Props { definition: AdventureDefinition; entries: LibraryEntry[]; onChange: (value: AdventureDefinition) => void }
const stats = [['hp', '生命上限'], ['ep', '能量上限'], ['pp', '体力上限'], ['attack', '火力'], ['defence', '装甲'], ['speed', '机动'], ['iq', '资质'], ['knowledge', '学识'], ['resist', '抗性']] as const
const models = FIGURE_MODELS
const customTypes = { text: '文字', number: '数值', boolean: '开关', resource: '资源条' }

export default function RpgCharacterStudio({ definition, entries, onChange }: Props) {
  const latest = useRef(definition); latest.current = definition
  const mounted = useRef(true)
  useEffect(() => { mounted.current = true; return () => { mounted.current = false } }, [])
  const db = definition.rpg!
  const [group, setGroup] = useState<RpgCharacterGroup>('roles'), [selected, setSelected] = useState('hero'), [preset, setPreset] = useState('wanderer'), [notice, setNotice] = useState(''), [uploading, setUploading] = useState(false)
  const imageInput = useRef<HTMLInputElement>(null)
  const id = db[group][selected] ? selected : Object.keys(db[group])[0], template = db[group][id]
  const card = template ? configuredRpgCard(definition, id, group) ?? defaultRpgCard(db, id, group) : undefined
  function update(fn: (next: AdventureDefinition, card: TavernCard) => void) {
    try {
      const next = withRpgCharacterCard(latest.current, id, group), target = configuredRpgCard(next, id, group)!
      target.sheet ??= defaultRpgCard(next.rpg!, id, group).sheet
      fn(next, target); target.updatedAt = new Date().toISOString()
      onChange(refreshRpgCardValues(next)); setNotice('')
    } catch (error) { setNotice((error as Error).message) }
  }
  function create(copy = false) {
    try {
      const next = structuredClone(definition), newId = `${group === 'roles' ? 'role' : 'enemy'}_${crypto.randomUUID().slice(0, 8)}`
      next.rpg![group][newId] = copy && template ? { ...structuredClone(template), name: `${template.name.slice(0, 112)} · 副本` } : { name: group === 'roles' ? '新角色' : '新敌人', hp: 120, ep: 50, pp: 100, attack: 14, defence: 8, speed: 16, iq: 50, color: '#7eabb2' }
      const prepared = withRpgCharacterCard(next, newId, group)
      if (copy && card) {
        const cloned = structuredClone(card), target = configuredRpgCard(prepared, newId, group)!
        Object.assign(target, cloned, { id: target.id, name: prepared.rpg![group][newId].name, updatedAt: new Date().toISOString() })
      }
      onChange(refreshRpgCardValues(prepared)); setSelected(newId); setNotice(group === 'roles' ? '角色已创建，可在剧情脚本中使用“队友入队”。' : '敌人已创建，可在剧情脚本的“战术遭遇”中选择。')
    } catch (error) { setNotice((error as Error).message) }
  }
  async function portrait(file?: File) {
    if (!file || uploading) return
    const ownerId = id, ownerGroup = group, ownerWork = definition.id
    setUploading(true); setNotice('正在保存肖像…')
    try {
      if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 1_400_000) throw new Error('请选择不超过1.4 MB的 PNG、JPEG 或 WebP 图片。')
      const resource = await uploadLibraryResource(file)
      // Selection controls are disabled while the upload is in progress.
      if (mounted.current && latest.current.id === ownerWork && ownerId === id && ownerGroup === group) update((next, c) => { c.portrait = resource.url; next.rpg![group][id].tabletopAppearance ??= createObject('figurine', { metadata: { model: 'ranger', tavernPortrait: true } }) })
    } catch (error) { setNotice((error as Error).message) } finally { setUploading(false) }
  }
  function fieldEdit(fieldId: string, fn: (field: TavernField, c: TavernCard) => void) { update((_, c) => { const f = c.sheet!.schema.modules.flatMap(m => m.fields).find(f => f.id === fieldId); if (f) fn(f, c) }) }
  const appearance = template?.tabletopAppearance as ReturnType<typeof createObject> | undefined
  const preview = template ? structuredClone(appearance ?? createObject('figurine', { id: 'character-preview', metadata: { model: 'ranger' } })) : undefined
  if (preview) { preview.color = template.color ?? '#7eabb2'; if (card?.portrait && preview.metadata.tavernPortrait !== false) { preview.texture = card.portrait; preview.metadata.model = '' } }
  const livePreview = rpgAuthorCardPreview(definition, id, group)
  const character = template ? makeRpgCharacter(template, db, group === 'enemies') : undefined
  const custom = card?.sheet?.schema.modules.flatMap(m => m.fields).filter(f => !f.id.startsWith('rpg_')) ?? []
  return <div className="rpg-character-studio">
    <div className="rpg-character-toolbar"><div><small>人物 · 棋子 · 规则</small><h2>角色卡与棋子</h2><p>配置一次，探索棋子、战斗与角色卡共用。</p></div><button onClick={() => { try { onChange(refreshRpgCardValues(withRpgPartyCards(definition))); setNotice('全队角色卡已生成，已有档案与自定义字段已保留。') } catch (error) { setNotice((error as Error).message) } }}><Cards size={18} />一键生成全队角色卡</button></div>
    {notice && <p className="rpg-character-notice" role="status">{notice}</p>}
    <div className="rpg-character-picker"><label>人物分类<select disabled={uploading} value={group} onChange={e => { const g = e.target.value as RpgCharacterGroup; setGroup(g); setSelected(Object.keys(db[g])[0]); setNotice('') }}><option value="roles">主角与队友</option><option value="enemies">敌人与遭遇</option></select></label><label>配置人物<select disabled={uploading} value={id ?? ''} onChange={e => { setSelected(e.target.value); setNotice('') }}>{Object.entries(db[group]).map(([key, t]) => <option key={key} value={key}>{t.name}{key === 'hero' ? ' · 主角' : ''}</option>)}</select></label><button disabled={uploading || Object.keys(db[group]).length >= (group === 'roles' ? 128 : 256)} onClick={() => create()}><Plus size={17} />新建人物</button><button disabled={uploading || !template || Object.keys(db[group]).length >= (group === 'roles' ? 128 : 256)} onClick={() => create(true)}><Copy size={17} />复制配置</button></div>
    {!template || !card ? <p>还没有敌人，点击“新建人物”开始配置。</p> : <div className="rpg-character-layout"><div className="rpg-character-form">
      <section><h3>01 · 身份与形象</h3><div className="rpg-character-fields"><label>姓名<input maxLength={120} value={template.name} onChange={e => update((n, c) => { n.rpg![group][id].name = e.target.value; c.name = e.target.value })} /></label><label>称号<input maxLength={120} value={card.title} onChange={e => update((n, c) => { c.title = e.target.value; n.rpg![group][id].title = e.target.value })} /></label><label>棋子颜色<input type="color" value={template.color ?? '#7eabb2'} onChange={e => update(n => { n.rpg![group][id].color = e.target.value })} /></label></div><label>角色背景<textarea rows={3} maxLength={4000} value={card.profile.background} onChange={e => update((n, c) => { c.profile.background = e.target.value; n.rpg![group][id].desc = e.target.value })} /></label>
        <div className="rpg-character-fields"><label>棋子造型<select value={String(appearance?.metadata.model ?? 'ranger')} onChange={e => update(n => { n.rpg![group][id].tabletopAppearance = createObject('figurine', { metadata: { model: e.target.value, tavernPortrait: false } }) })}>{models.map(([key, name]) => <option key={key} value={key}>{name}</option>)}{appearance && !models.some(([key]) => key === appearance.metadata.model) && <option value={String(appearance.metadata.model ?? '')}>物件库自定义模型</option>}</select></label><label>从物件库取用<select value="" onChange={e => { const entry = entries.find(v => v.id === e.target.value); if (entry) update(n => { const o = instantiateLibraryEntry(entry); o.metadata.tavernPortrait = false; n.rpg![group][id].tabletopAppearance = o; n.rpg![group][id].color = o.color }) }}><option value="">{appearance ? '已配置棋子，选择可更换' : '选择自己的棋子模板'}</option>{entries.filter(e => e.kind === 'figurine').map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
        <div className="rpg-inline"><button disabled={uploading} onClick={() => imageInput.current?.click()}><UploadSimple size={17} />{uploading ? '上传中…' : '上传角色肖像'}</button>{card.portrait && <button disabled={uploading} onClick={() => update((_, c) => { c.portrait = '' })}>移除肖像</button>}<label className="rpg-character-check"><input type="checkbox" disabled={!card.portrait} checked={!!card.portrait && appearance?.metadata.tavernPortrait !== false} onChange={e => update(n => { const o = structuredClone(appearance ?? createObject('figurine', { metadata: { model: 'ranger' } })); o.metadata.tavernPortrait = e.target.checked; n.rpg![group][id].tabletopAppearance = o })} />棋子使用肖像立绘</label></div>
      </section>
      <section><h3>02 · 角色规则快速配置</h3><div className="rpg-inline"><label>职业模板<select value={preset} onChange={e => setPreset(e.target.value)}>{RPG_CHARACTER_PRESETS.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={() => { try { onChange(refreshRpgCardValues(applyRpgCharacterPreset(definition, id, preset, group))); setNotice('已应用基础属性与对应系别的初始武功，可继续调整。') } catch (error) { setNotice((error as Error).message) } }}>应用规则模板</button></div><p className="rpg-muted">模板会替换基础属性、专长与初始武功；装备与人物资料保留。保存后新开或重开对局使用新规则。</p><div className="rpg-character-fields rpg-number-fields">{stats.map(([key, label]) => <label key={key}>{label}<input type="number" min={key === 'hp' ? 1 : 0} max={1000000} value={Number(template[key] ?? (key === 'hp' ? 100 : key === 'ep' ? 40 : key === 'pp' ? 100 : character?.[key as keyof typeof character] ?? 0))} onChange={e => update(n => { n.rpg![group][id][key] = Number(e.target.value) })} /></label>)}<label>初始等级<input type="number" min="1" max="30" value={Number(template.level ?? 1)} onChange={e => update(n => { n.rpg![group][id].level = Number(e.target.value) })} /></label><label>能量谱系<select value={Number(template.ept ?? 2)} onChange={e => update(n => { n.rpg![group][id].ept = Number(e.target.value) })}><option value="0">暗物质</option><option value="1">光能</option><option value="2">通用</option></select></label></div><details><summary>六系专长与升级成长</summary><div className="rpg-character-fields rpg-number-fields">{RPG_SPECIALTIES.map(({ key, label }) => <label key={key}>{label}<input type="number" min="0" max="1000000" value={Number(template[key] ?? 0)} onChange={e => update(n => { n.rpg![group][id][key] = Number(e.target.value) })} /></label>)}</div><div className="rpg-character-fields rpg-number-fields">{(['hp', 'ep', 'attack', 'defence', 'speed'] as const).map((key, i) => <label key={key}>每级{['生命', '能量', '火力', '装甲', '机动'][i]}增加<input type="number" min="0" max="1000000" step="0.1" value={Number((template.growth as Record<string, number> | undefined)?.[key] ?? [20, 8, 2, 1, 1][i])} onChange={e => update(n => { const t = n.rpg![group][id]; t.growth = { ...(t.growth as object ?? {}), [key]: Number(e.target.value) } })} /></label>)}</div></details></section>
      <section><h3>03 · 武功、装备与携带物</h3>{character?.magics.map((skill, i) => <div className="rpg-character-skill" key={skill.id}><div><b>{(db.magics[skill.id] as RpgMagic).name}</b><small>{SCHOOL_NAMES[(db.magics[skill.id] as RpgMagic).school]} · {dicePoolLabel(rpgSkillDice(db, skill.id))}</small></div><label>熟练度<input type="number" min="1" max="999" value={skill.lv} onChange={e => update(n => { const values = character.magics.map(m => ({ ...m })); values[i].lv = Number(e.target.value); n.rpg![group][id].magics = values })} /></label><button aria-label={`移除武功${(db.magics[skill.id] as RpgMagic).name}`} onClick={() => update(n => { n.rpg![group][id].magics = character.magics.filter((_, index) => index !== i) })}>移除</button></div>)}<label>添加初始武功<select value="" disabled={(character?.magics.length ?? 0) >= 10} onChange={e => { if (e.target.value) update(n => { n.rpg![group][id].magics = [...character!.magics, { id: e.target.value, lv: 1 }] }) }}><option value="">选择武功，最多10门</option>{Object.entries(db.magics).filter(([key]) => !character?.magics.some(s => s.id === key)).map(([key, v]) => <option key={key} value={key}>{(v as RpgMagic).name}</option>)}</select></label><div className="rpg-character-fields">{(['weapon', 'armor'] as const).map((slot, index) => <label key={slot}>{index ? '初始防具' : '初始武器'}<select value={String(template[slot] ?? '')} onChange={e => update(n => { n.rpg![group][id][slot] = e.target.value || null })}><option value="">未装备</option>{Object.entries(db.items).filter(([, v]) => v.type === index + 1).map(([key, v]) => <option key={key} value={key}>{v.name}</option>)}</select></label>)}</div>
        {group === 'roles' && <details><summary>入队时带入共享背包</summary>{(template.brings ?? []).map((item, index) => <div className="rpg-inline" key={`${item.id}-${index}`}><span>{db.items[item.id].name}</span><label>数量<input type="number" min="1" max="999" value={item.n} onChange={e => update(n => { n.rpg![group][id].brings![index].n = Number(e.target.value) })} /></label><button onClick={() => update(n => { n.rpg![group][id].brings!.splice(index, 1) })}>移除</button></div>)}<select aria-label="添加携带物品" value="" onChange={e => { if (e.target.value) update(n => { const t = n.rpg![group][id]; t.brings ??= []; const item = t.brings.find(v => v.id === e.target.value); if (item) item.n = Math.min(999, item.n + 1); else t.brings.push({ id: e.target.value, n: 1 }) }) }}><option value="">＋添加携带物品</option>{Object.entries(db.items).map(([key, item]) => <option key={key} value={key}>{item.name}</option>)}</select></details>}
      </section>
      <section><h3>04 · 自定义角色卡字段</h3><p className="rpg-muted">阵营、种族、职业、关系或个人资源都能增设。标为主持私密的字段在玩家卡面隐藏。</p>{custom.map(f => { const value = card.sheet!.values[f.id]; return <div className="rpg-custom-field" key={f.id}><input aria-label={`字段名称${f.label}`} maxLength={120} value={f.label} onChange={e => fieldEdit(f.id, v => { v.label = e.target.value })} /><select aria-label={`${f.label}字段类型`} value={f.type} disabled={!Object.hasOwn(customTypes, f.type)} onChange={e => fieldEdit(f.id, (v, c) => { v.type = e.target.value; for (const key of ['min', 'max', 'step', 'options', 'expression']) delete (v as unknown as Record<string, unknown>)[key]; v.default = v.type === 'number' ? 0 : v.type === 'boolean' ? false : v.type === 'resource' ? { value: 0, max: 100 } : ''; c.sheet!.values[f.id] = structuredClone(v.default) })}>{Object.entries(customTypes).map(([key, name]) => <option key={key} value={key}>{name}</option>)}{!Object.hasOwn(customTypes, f.type) && <option value={f.type}>高级字段 · 请在完整角色工具编辑</option>}</select>
          {f.type === 'resource' ? <div className="rpg-field-resource"><input aria-label={`${f.label}当前值`} type="number" min="0" max="1000000" value={Number((value as { value: number })?.value ?? 0)} onChange={e => fieldEdit(f.id, (_, c) => { c.sheet!.values[f.id] = { ...(value as object), value: Number(e.target.value) } })} /><span>/</span><input aria-label={`${f.label}最大值`} type="number" min="0" max="1000000" value={Number((value as { max: number })?.max ?? 100)} onChange={e => fieldEdit(f.id, (_, c) => { c.sheet!.values[f.id] = { ...(value as object), max: Number(e.target.value) } })} /></div> : f.type === 'boolean' ? <label className="rpg-character-check"><input type="checkbox" aria-label={`${f.label}值`} checked={Boolean(value)} onChange={e => fieldEdit(f.id, (_, c) => { c.sheet!.values[f.id] = e.target.checked })} />启用</label> : ['text', 'number'].includes(f.type) ? <input aria-label={`${f.label}值`} type={f.type === 'number' ? 'number' : 'text'} maxLength={2000} value={String(value ?? '')} onChange={e => fieldEdit(f.id, (_, c) => { c.sheet!.values[f.id] = f.type === 'number' ? Number(e.target.value) : e.target.value })} /> : <span>保留原始数据</span>}
          <label className="rpg-character-check"><input type="checkbox" checked={!!f.private} onChange={e => fieldEdit(f.id, v => { v.private = e.target.checked })} />主持私密</label><button aria-label={`删除字段${f.label}`} onClick={() => update((_, c) => { for (const m of c.sheet!.schema.modules) m.fields = m.fields.filter(v => v.id !== f.id); delete c.sheet!.values[f.id] })}>删除</button></div> })}<button onClick={() => update((_, c) => { const fields = c.sheet!.schema.modules.flatMap(m => m.fields); if (fields.length >= 250) throw new Error('每张角色卡最多250个字段。'); let m = c.sheet!.schema.modules.find(v => v.id === 'rpg_custom'); if (!m) { m = { id: 'rpg_custom', name: '自定义资料', fields: [] }; c.sheet!.schema.modules.push(m) } const key = `custom_${crypto.randomUUID().slice(0, 8)}`; m.fields.push({ id: key, label: '新字段', type: 'text' }); c.sheet!.values[key] = '' })}><Plus size={16} />添加自定义字段</button>
        <details><summary>选择卡面显示的游戏属性</summary><p className="rpg-muted">这里调整卡面标签与显示项目。对局数值由游戏规则同步。</p><div className="rpg-card-field-options">{RPG_CARD_FIELDS.map(f => { const field = card.sheet?.schema.modules.flatMap(m => m.fields).find(v => v.id === f.id); return <div key={f.id}><label className="rpg-character-check"><input type="checkbox" checked={!!field} onChange={e => update((_, c) => { if (e.target.checked) { let m = c.sheet!.schema.modules.find(v => v.id === 'rpg_rules'); if (!m) { m = { id: 'rpg_rules', name: '对局资料', fields: [] }; c.sheet!.schema.modules.push(m) } m.fields.push({ ...f }) } else { for (const m of c.sheet!.schema.modules) m.fields = m.fields.filter(v => v.id !== f.id); delete c.sheet!.values[f.id] } })} />{f.label}</label>{field && <input aria-label={`${f.label}卡面标签`} maxLength={120} value={field.label} onChange={e => fieldEdit(f.id, v => { v.label = e.target.value })} />}</div> })}</div></details>
      </section>
    </div><aside className="rpg-card-preview"><small>玩家卡面预览</small><div className="rpg-figurine-preview">{preview && <Suspense fallback={<span>载入棋子…</span>}><ObjectPreview object={preview} /></Suspense>}</div><div className="rpg-preview-identity">{card.portrait ? <img src={card.portrait} alt={`${card.name}肖像`} /> : <UserCircle size={48} weight="duotone" />}<div><h2>{template.name || '未命名角色'}</h2><p>{card.title || '冒险者'}</p><small>{group === 'roles' ? '主角与队友' : '遭遇敌人'} · Lv.{character?.level}</small></div></div><dl>{livePreview && characterRows(livePreview.card, livePreview.archive).filter(r => r.value).map((r, index) => <div key={index}><dt>{r.label}</dt><dd>{r.value}</dd></div>)}</dl><p className="rpg-muted">玩家卡面隐藏主持私密字段。生命、能量、装备和武功会随对局同步。</p></aside></div>}
    <input hidden ref={imageInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { void portrait(e.target.files?.[0]); e.target.value = '' }} />
  </div>
}
