import { useState } from 'react'
import { RPG_OPS, type RpgCondition, type RpgDatabase, type RpgOp, type RpgOpName } from '../lib/rpg-schema'
export function defaultRpgOp(name: RpgOpName, db: RpgDatabase): RpgOp {
  const first = (rows: object) => Object.keys(rows)[0] ?? ''
  const data: Partial<Record<RpgOpName, Partial<RpgOp>>> = { talk: { name: '旁白', text: '写下这段剧情。' }, choice: { text: '你要怎么做？', options: [{ t: '继续探索', s: [] }] }, if: { cond: { flag: 'story_flag' }, then: [], else: [] }, battle: { title: '新的遭遇', enemies: [first(db.enemies)], onWin: [] }, get: { item: first(db.items), n: 1 }, loseItem: { item: first(db.items) }, money: { v: 100 }, core: { n: 1 }, flag: { name: 'story_flag', v: 1 }, join: { role: first(db.roles) }, leave: { role: Object.keys(db.roles).find(r => r !== 'hero') ?? 'hero' }, morality: { v: 1 }, fame: { v: 1 }, shop: { id: first(db.shops) }, setTile: { x: 1, y: 1, ch: '.' }, music: { m: 'town' }, sfx: { name: 'get' } }
  return { op: name, ...data[name] }
}
const conditionLabels: Record<keyof RpgCondition, string> = { flag: '开关成立', flagNot: '开关未成立', has: '持有物品', cores: '目标数量至少', morality: '倾向至少', moralityBelow: '倾向低于', moralityAtMost: '倾向至多', moneyAtLeast: '货币至少', rnd: '随机概率 0–1', inParty: '队友在队', notInParty: '队友不在队' }
export default function RpgScriptEditor({ value, db, onChange, depth = 0 }: { value: RpgOp[]; db: RpgDatabase; onChange: (v: RpgOp[]) => void; depth?: number }) {
  const [add, setAdd] = useState<RpgOpName>('talk')
  const patch = (i: number, values: Partial<RpgOp>) => onChange(value.map((o, n) => n === i ? { ...o, ...values } : o))
  const select = (label: string, current: string | undefined, rows: Record<string, { name: string }>, change: (v: string) => void) => <label>{label}<select value={current ?? ''} onChange={e => change(e.target.value)}><option value="">请选择</option>{Object.entries(rows).map(([id, row]) => <option key={id} value={id}>{row.name} · {id}</option>)}</select></label>
  return <div className="rpg-script" style={{ '--nest': depth } as React.CSSProperties}>
    {value.map((op, i) => <details className="rpg-op" key={i} open={depth === 0 && value.length < 10}>
      <summary><span>{i + 1}. {RPG_OPS[op.op]}</span><small>{op.text?.slice(0, 28) || op.name || op.item || op.role || ''}</small></summary>
      <div className="rpg-op-body"><div className="rpg-inline"><select aria-label="指令类型" value={op.op} onChange={e => onChange(value.map((o, n) => n === i ? defaultRpgOp(e.target.value as RpgOpName, db) : o))}>{Object.entries(RPG_OPS).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><button disabled={!i} onClick={() => { const v = [...value]; [v[i - 1], v[i]] = [v[i], v[i - 1]]; onChange(v) }}>↑</button><button disabled={i === value.length - 1} onClick={() => { const v = [...value]; [v[i + 1], v[i]] = [v[i], v[i + 1]]; onChange(v) }}>↓</button><button onClick={() => onChange(value.filter((_, n) => n !== i))}>删除</button></div>
        {['talk', 'choice'].includes(op.op) && <label>剧情文字<textarea rows={3} maxLength={8000} value={op.text ?? ''} onChange={e => patch(i, { text: e.target.value })} /></label>}
        {op.op === 'talk' && <div className="rpg-inline"><label>说话人<input maxLength={120} value={op.name ?? ''} onChange={e => patch(i, { name: e.target.value })} /></label><label>颜色<input type="color" value={op.color || '#cbb88b'} onChange={e => patch(i, { color: e.target.value })} /></label></div>}
        {['get', 'loseItem'].includes(op.op) && select('物品', op.item, db.items, item => patch(i, { item }))}
        {['join', 'leave'].includes(op.op) && select('角色', op.role, db.roles, role => patch(i, { role }))}
        {['get', 'core'].includes(op.op) && <label>{op.op === 'core' ? `目标编号 1–${db.settings?.objectiveCount ?? 12}` : '数量'}<input type="number" min="1" max={op.op === 'core' ? db.settings?.objectiveCount ?? 12 : 999} value={op.n ?? 1} onChange={e => patch(i, { n: Number(e.target.value) })} /></label>}
        {['money', 'morality', 'fame', 'flag'].includes(op.op) && <label>{op.op === 'flag' ? '开关值（0关闭，1成立）' : '增减数值'}<input type="number" value={op.v ?? 1} onChange={e => patch(i, { v: Number(e.target.value) })} /></label>}
        {['flag', 'sfx'].includes(op.op) && <label>{op.op === 'flag' ? '开关标识' : '音效名'}<input maxLength={120} value={op.name ?? ''} onChange={e => patch(i, { name: e.target.value })} /></label>}
        {op.op === 'music' && <label>音乐名<input value={op.m ?? ''} onChange={e => patch(i, { m: e.target.value })} /><small>内置：town / world / battle / boss / sad / end / title；空值停止。</small></label>}
        {op.op === 'shop' && select('商店', op.id, Object.fromEntries(Object.keys(db.shops).map(id => [id, { name: id }])), id => patch(i, { id }))}
        {op.op === 'setTile' && <div className="rpg-inline">{(['x', 'y'] as const).map(k => <label key={k}>{k.toUpperCase()}<input type="number" min="0" value={op[k] ?? 0} onChange={e => patch(i, { [k]: Number(e.target.value) })} /></label>)}<label>地形<select value={op.ch ?? '.'} onChange={e => patch(i, { ch: e.target.value })}>{['.', '#', ',', 'K', 'S', 'G', 'R', 'D', 'W', 'T', 'B', 'X'].map(t => <option key={t}>{t}</option>)}</select></label></div>}
        {op.op === 'choice' && <>{op.options?.map((option, n) => <div className="rpg-branch" key={n}><div className="rpg-inline"><label>选项 {n + 1}<input maxLength={500} value={option.t} onChange={e => patch(i, { options: op.options!.map((v, j) => n === j ? { ...v, t: e.target.value } : v) })} /></label><button onClick={() => patch(i, { options: op.options!.filter((_, j) => j !== n) })}>删除选项</button></div><RpgScriptEditor depth={depth + 1} value={option.s} db={db} onChange={s => patch(i, { options: op.options!.map((v, j) => n === j ? { ...v, s } : v) })} /></div>)}<button disabled={(op.options?.length ?? 0) >= 12 || depth >= 12} onClick={() => patch(i, { options: [...op.options ?? [], { t: '新选项', s: [] }] })}>＋选项与后续剧情</button></>}
        {op.op === 'if' && <><p className="rpg-muted">所有已启用条件同时满足，才执行“满足”分支。</p><div className="rpg-condition-grid">{(Object.keys(conditionLabels) as (keyof RpgCondition)[]).map(k => { const isNumber = ['cores', 'morality', 'moralityBelow', 'moralityAtMost', 'moneyAtLeast', 'rnd'].includes(k); const rows = k === 'has' ? db.items : ['inParty', 'notInParty'].includes(k) ? db.roles : undefined; return <label key={k}><span><input type="checkbox" checked={op.cond?.[k] !== undefined} onChange={e => { const cond = { ...op.cond }; if (!e.target.checked) delete cond[k]; else Object.assign(cond, { [k]: isNumber ? k === 'rnd' ? .5 : 1 : rows ? Object.keys(rows)[0] : 'story_flag' }); patch(i, { cond }) }} />{conditionLabels[k]}</span>{op.cond?.[k] !== undefined && (rows ? <select value={String(op.cond[k])} onChange={e => patch(i, { cond: { ...op.cond, [k]: e.target.value } })}>{Object.entries(rows).map(([id, row]) => <option key={id} value={id}>{row.name}</option>)}</select> : <input type={isNumber ? 'number' : 'text'} step={k === 'rnd' ? .05 : 1} value={op.cond[k]} onChange={e => patch(i, { cond: { ...op.cond, [k]: isNumber ? Number(e.target.value) : e.target.value } })} />)}</label> })}</div>{(['then', 'else'] as const).map(key => <div className="rpg-branch" key={key}><h4>{key === 'then' ? '条件满足' : '条件不满足'}</h4><RpgScriptEditor depth={depth + 1} value={op[key] ?? []} db={db} onChange={v => patch(i, { [key]: v })} /></div>)}</>}
        {op.op === 'battle' && <><label>遭遇标题<input value={op.title ?? ''} onChange={e => patch(i, { title: e.target.value })} /></label>{op.enemies?.map((id, n) => <div className="rpg-inline" key={n}>{select(`敌人 ${n + 1}`, id, db.enemies, id => patch(i, { enemies: op.enemies!.map((v, j) => j === n ? id : v) }))}<button onClick={() => patch(i, { enemies: op.enemies!.filter((_, j) => j !== n) })}>移除</button></div>)}<button disabled={(op.enemies?.length ?? 0) >= 18} onClick={() => patch(i, { enemies: [...op.enemies ?? [], Object.keys(db.enemies)[0]] })}>＋敌人</button><div className="rpg-branch"><h4>战胜后继续</h4><RpgScriptEditor depth={depth + 1} value={op.onWin ?? []} db={db} onChange={onWin => patch(i, { onWin })} /></div></>}
        {op.op === 'ending' && <p className="rpg-muted">进入胜利结局并结束本局。可在前面用条件分支和对话定义不同的结局。</p>}
      </div>
    </details>)}
    <div className="rpg-inline rpg-script-add"><select aria-label="添加剧情指令" value={add} onChange={e => setAdd(e.target.value as RpgOpName)}>{Object.entries(RPG_OPS).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><button disabled={depth > 12 || value.length >= 256} onClick={() => onChange([...value, defaultRpgOp(add, db)])}>＋指令</button></div>
  </div>
}
