import { useEffect, useRef, useState } from 'react'
import type { AdventureDefinition } from '../lib/adventure-schema'
import { adventureFromRpg, blankRpgAdventure, rpgSceneId } from '../lib/rpg-engine'
import { validateRpgDatabase, type RpgDatabase, type RpgMap, type RpgOp } from '../lib/rpg-schema'
import { saveAdventure } from '../lib/adventure-library'
import { exportPortableAdventure, importPortableAdventure, instantiateLibraryEntry, type LibraryEntry } from '../lib/object-library'
import RpgScriptEditor from './RpgScriptEditor'
import RpgSkillStudio from './RpgSkillStudio'
import RpgCharacterStudio from './RpgCharacterStudio'
import { refreshRpgCardValues } from '../lib/rpg-character-cards'
import { SCHOOL_NAMES, type RpgMagic } from '../lib/rpg-rules'
import { rpgTextEnabled } from '../lib/rpg-text-presentation'
import './rpg-tools.css'
interface Props { initialTab?: 'map' | 'characters'; initialDefinition: AdventureDefinition; entries: LibraryEntry[]; onClose: (d: AdventureDefinition) => void; onPlay: (d: AdventureDefinition) => void; onEditScene: (d: AdventureDefinition, id: string) => void }
const CACHE = 'bear-trpg-rpg-author-draft-v1'
const terrain = { '.': '通路', '#': '墙壁', ',': '暗色通路', K: '平台', S: '沙地', G: '草地', R: '岩石', D: '地板', W: '传送标识', T: '终端障碍', B: '箱体障碍', X: '世界出口' }
const palette: Record<string, string> = { '.': '#435b68', '#': '#29333c', ',': '#304452', K: '#527d8f', S: '#817158', G: '#476554', R: '#5e5b61', D: '#75858a', W: '#778cb0', T: '#568b9d', B: '#9b7857', X: '#549c82' }
function download(name: string, data: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
export default function RpgStudio({ initialTab = 'map', initialDefinition, entries, onClose, onPlay, onEditScene }: Props) {
  const [base, setBase] = useState(() => structuredClone(initialDefinition)), [db, setDb] = useState(() => structuredClone(initialDefinition.rpg!))
  const [mapId, setMapId] = useState(() => initialDefinition.startSceneId.replace('rpg-map-', '')), [tab, setTab] = useState<'map' | 'data' | 'characters' | 'skills' | 'world'>(initialTab)
  const [target, setTarget] = useState<{ kind: 'events' | 'npcs'; index: number }>(), [brush, setBrush] = useState('.')
  const [painting, setPainting] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [dirty, setDirty] = useState(false), [cacheStatus, setCacheStatus] = useState('')
  const [category, setCategory] = useState<'roles' | 'enemies' | 'items'>('roles'), [dataId, setDataId] = useState('hero')
  const [raw, setRaw] = useState(''), input = useRef<HTMLInputElement>(null)
  const [previous] = useState(() => { try { return localStorage.getItem(CACHE) } catch { return null } })
  const map = db.maps[mapId] ?? Object.values(db.maps)[0], row = target && map[target.kind][target.index], template = db[category][dataId]
  useEffect(() => { setRaw(template ? JSON.stringify(template, null, 2) : '') }, [dataId, category, template])
  useEffect(() => { const timer = setTimeout(() => { try { localStorage.setItem(CACHE, JSON.stringify({ base, db, dirty })); setCacheStatus('浏览器草稿已缓存') } catch { setCacheStatus('草稿缓存已满，请保存或导出') } }, 700); return () => clearTimeout(timer) }, [base, db, dirty])
  function edit(fn: (draft: RpgDatabase) => void) { setDb(d => { const n = structuredClone(d); fn(n); return n }); setDirty(true) }
  const changeMap = (v: Partial<RpgMap>) => edit(d => Object.assign(d.maps[mapId], v))
  function compiled() { return adventureFromRpg(db, refreshRpgCardValues({ ...base, rpg: db })) }
  async function run(fn: () => void | Promise<void>) { if (busy) return; setBusy(true); setNotice(''); try { await fn() } catch (e) { setNotice((e as Error).message) } finally { setBusy(false) } }
  async function save() { const d = await saveAdventure(compiled()); setBase(d); setDb(d.rpg!); setDirty(false); setNotice(`已保存「${d.title}」版本 ${d.revision}，可从游戏库重新打开。`); return d }
  function editRow(v: object) { if (target) edit(d => Object.assign(d.maps[mapId][target.kind][target.index], v)) }
  function resize(w: number, h: number) {
    if (!Number.isSafeInteger(w) || !Number.isSafeInteger(h) || w < 4 || h < 4 || w > 64 || h > 64) { setNotice('地图行列需要4–64的整数。'); return }
    if ([map.entry, ...map.npcs, ...map.events].some(c => c.x >= w || c.y >= h)) { setNotice('缩小前请先把入口、NPC和事件移到保留区域。'); return }
    changeMap({ w, h, tiles: Array.from({ length: h }, (_, y) => (map.tiles[y] ?? '#'.repeat(w)).slice(0, w).padEnd(w, '#')) })
  }
  function createMap() { const id = `map_${crypto.randomUUID().slice(0, 8)}`; edit(d => { d.maps[id] = { name: '新场景', w: 12, h: 10, entry: { x: 1, y: 1 }, music: 'town', tiles: Array.from({ length: 10 }, (_, y) => y === 0 || y === 9 ? '#'.repeat(12) : `#${'.'.repeat(10)}#`), npcs: [], events: [], board: { cellSize: 1, color: '#435b68' } }; d.world.locations.push({ id, name: '新场景', x: 1, y: 1, desc: '新的探索区域。' }) }); setMapId(id); setTarget(undefined) }
  function createTrigger(kind: 'events' | 'npcs') { const script: RpgOp[] = [{ op: 'talk', name: '旁白', text: '从这里编写剧情。' }]; const index = map[kind].length; edit(d => { const m = d.maps[mapId]; if (kind === 'events') m.events.push({ id: `event_${crypto.randomUUID().slice(0, 8)}`, name: '新事件', x: m.entry.x, y: m.entry.y, trigger: 'interact', once: false, script }); else m.npcs.push({ name: '新NPC', x: Math.min(m.w - 1, m.entry.x + 1), y: m.entry.y, script, blocking: true }) }); setTarget({ kind, index }); setPainting(false) }
  async function importFile(file?: File) { if (!file) return; await run(async () => { if (file.size > 5_000_000) throw new Error('内容包最多5 MB。'); const value = JSON.parse(await file.text()); let next: AdventureDefinition; if (value.format === 'realm-adventure') { next = await importPortableAdventure(value); if (!next.rpg) throw new Error('此作品不是坐标事件RPG，请在故事编辑器打开。') } else { next = adventureFromRpg(value.db ?? value); next.title = '导入的桌面 RPG' } try { localStorage.setItem(`${CACHE}-previous`, JSON.stringify({ base, db, dirty })) } catch { /* The live draft remains until the replacement is ready. */ } setBase(next); setDb(next.rpg!); setMapId(next.startSceneId.replace('rpg-map-', '')); setTarget(undefined); setDirty(true); setNotice('内容已导入为独立作品。RPG 工具导出的 {v, db} JSON 可直接使用。') }) }
  return <div className="rpg-studio">
    <header className="rpg-studio-header"><div><small>熊酒馆 · RPG 内容编辑器</small><h1>剧情工具</h1></div><input aria-label="作品名称" maxLength={120} value={base.title} onChange={e => { setBase(d => ({ ...d, title: e.target.value })); setDirty(true) }} /><div className="rpg-inline"><button disabled={busy} onClick={() => void run(async () => { await save() })}>{dirty ? '保存作品 *' : '保存作品'}</button><button disabled={busy} onClick={() => void run(async () => { if (dirty) await save(); const d = blankRpgAdventure(); setBase(d); setDb(d.rpg!); setMapId("camp"); setTarget(undefined); setDirty(true); setNotice("已创建探索、交谈、遭遇与交付的完整 RPG 示例。") })}>新建 RPG</button><button disabled={busy} onClick={() => input.current?.click()}>导入 RPG JSON</button><button disabled={busy} onClick={() => void run(async () => download(`${base.title}.adventure.json`, await exportPortableAdventure(compiled())))}>导出创作包</button><button className="rpg-primary" disabled={busy} onClick={() => void run(async () => onPlay(await save()))}>保存并试玩</button><button disabled={busy} onClick={() => void run(() => onClose(compiled()))}>返回桌面</button></div></header>
    <div className="rpg-studio-notice" role="status">{notice || `${cacheStatus} · ${Object.keys(db.maps).length}张地图 / ${Object.keys(db.roles).length}个角色 / ${Object.keys(db.items).length}件物品`}</div>
    <div className="rpg-studio-body"><aside className="rpg-project-tree"><nav className="rpg-studio-tabs">{[['map', '地图与剧情'], ['characters', '角色卡与棋子'], ['data', '角色与物品'], ['skills', '武功与技能卡'], ['world', '世界与作品']].map(([id, name]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id as typeof tab)}>{name}</button>)}</nav>
      {tab === 'characters' && <p className="rpg-muted">主角、队友与敌人支持独立配置。自定义棋子从物件库取用；角色卡字段随作品一起保存和导入。</p>}
      {tab === 'map' && <><h3>场景地图</h3>{Object.entries(db.maps).map(([id, m]) => <button className={mapId === id ? 'active' : ''} key={id} onClick={() => { setMapId(id); setTarget(undefined); setPainting(false) }}>{m.name}<small>{m.w} × {m.h} · {id}</small></button>)}<button onClick={createMap}>＋新场景</button></>}
      {tab === 'data' && <><select value={category} aria-label="资料库分类" onChange={e => { const c = e.target.value as typeof category; setCategory(c); setDataId(Object.keys(db[c])[0]) }}><option value="roles">角色</option><option value="enemies">敌人</option><option value="items">物品</option></select>{Object.entries(db[category]).map(([id, t]) => <button key={id} className={dataId === id ? 'active' : ''} onClick={() => setDataId(id)}>{t.name}<small>{id}</small></button>)}<button onClick={() => { const id = `${category.slice(0, 1)}_${crypto.randomUUID().slice(0, 8)}`; edit(d => { d[category][id] = { name: '新条目', desc: '', ...(category !== 'items' ? { hp: 120, attack: 14, defence: 8 } : { price: 10 }) } }); setDataId(id) }}>＋新条目</button></>}
      {tab === 'skills' && <p className="rpg-muted">在右侧定义每门武功的技能卡与骰组，可从后台库取用自己的符号骰。</p>}
      {tab === 'world' && <p className="rpg-muted">作品版本存入本机作品库；对局保存剧情游标、队伍、背包、地形和开关。编辑作品不会改写已开始的对局。</p>}
    </aside><main className="rpg-author-main">
      {tab === 'map' && <><section className="rpg-map-spec"><h2>{map.name}</h2><div className="rpg-inline"><label>场景名称<input value={map.name} onChange={e => changeMap({ name: e.target.value })} /></label><label>列数<input type="number" min="4" max="64" value={map.w} onChange={e => resize(Number(e.target.value), map.h)} /></label><label>行数<input type="number" min="4" max="64" value={map.h} onChange={e => resize(map.w, Number(e.target.value))} /></label><label>格子尺寸<input type="number" min="0.5" max="2" step="0.1" value={map.board?.cellSize ?? 1} onChange={e => changeMap({ board: { color: map.board?.color ?? '#435b68', cellSize: Number(e.target.value) } })} /></label><label>底色<input type="color" value={map.board?.color ?? '#435b68'} onChange={e => changeMap({ board: { cellSize: map.board?.cellSize ?? 1, color: e.target.value } })} /></label></div><div className="rpg-inline">{(['x', 'y'] as const).map(k => <label key={k}>入口 {k.toUpperCase()}<input type="number" min="0" max={k === 'x' ? map.w - 1 : map.h - 1} value={map.entry[k]} onChange={e => changeMap({ entry: { ...map.entry, [k]: Number(e.target.value) } })} /></label>)}<label>地图音乐<input value={map.music ?? ''} onChange={e => changeMap({ music: e.target.value })} /></label><button onClick={() => { setBase(d => ({ ...d, startSceneId: rpgSceneId(mapId) })); setDirty(true) }}>{base.startSceneId === rpgSceneId(mapId) ? '当前开场' : '设为开场'}</button><button onClick={() => void run(() => onEditScene(compiled(), rpgSceneId(mapId)))}>布置3D场景与自定义物件</button></div><p className="rpg-muted">场景板自动留出四格桌沿，总规格不超过80单位。坐标从左上角(0,0)开始。实体地形合并生成，避免每格都创建物理物件。</p></section>
      <section><div className="rpg-inline"><button className={painting ? 'active' : ''} onClick={() => setPainting(!painting)}>{painting ? '正在绘制地形' : '启用地形笔刷'}</button><select aria-label="地形笔刷" value={brush} onChange={e => setBrush(e.target.value)}>{Object.entries(terrain).map(([id, name]) => <option key={id} value={id}>{id} · {name}</option>)}</select><small>{target ? '选择格子可移动当前事件 / NPC' : '选择下方事件或NPC后，点格子定位'}</small></div><div className="rpg-map-scroll"><div className="rpg-tile-map" style={{ gridTemplateColumns: `repeat(${map.w}, 25px)` }}>{map.tiles.flatMap((line, y) => [...line].map((ch, x) => { const npc = map.npcs.findIndex(n => n.x === x && n.y === y), ev = map.events.findIndex(e => e.x === x && e.y === y); return <button aria-label={`格子 ${x},${y} ${terrain[ch as keyof typeof terrain]}`} title={`(${x},${y}) ${npc >= 0 ? map.npcs[npc].name : ev >= 0 ? map.events[ev].id : terrain[ch as keyof typeof terrain]}`} key={`${x},${y}`} className={row?.x === x && row.y === y ? 'selected' : ''} style={{ background: palette[ch] }} onClick={() => { if (painting) changeMap({ tiles: map.tiles.map((l, i) => i === y ? l.slice(0, x) + brush + l.slice(x + 1) : l) }); else if (target) editRow({ x, y }); else if (npc >= 0) setTarget({ kind: 'npcs', index: npc }); else if (ev >= 0) setTarget({ kind: 'events', index: ev }) }}>{map.entry.x === x && map.entry.y === y ? '起' : npc >= 0 ? '人' : ev >= 0 ? map.events[ev].trigger === 'step' ? '◆' : '!' : ''}</button> }) )}</div></div></section>
      <section><h3>NPC 与坐标事件</h3><div className="rpg-trigger-list">{map.npcs.map((n, index) => <button key={`npc${index}`} className={target?.kind === 'npcs' && target.index === index ? 'active' : ''} onClick={() => { setTarget({ kind: 'npcs', index }); setPainting(false) }}>{n.name} <small>({n.x},{n.y})</small></button>)}{map.events.map((e, index) => <button key={e.id} className={target?.kind === 'events' && target.index === index ? 'active' : ''} onClick={() => { setTarget({ kind: 'events', index }); setPainting(false) }}>{e.name ?? e.id} <small>{e.trigger === 'step' ? '经过' : '交互'} ({e.x},{e.y})</small></button>)}<button onClick={() => createTrigger('npcs')}>＋NPC</button><button onClick={() => createTrigger('events')}>＋事件</button></div></section>
      {row && target && <section><h3>{target.kind === 'npcs' ? 'NPC 对话脚本' : '坐标事件脚本'}</h3><div className="rpg-inline"><label>{target.kind === 'npcs' ? '名称' : 'ID'}<input value={'trigger' in row ? row.id : row.name} onChange={e => editRow({ [target.kind === 'npcs' ? 'name' : 'id']: e.target.value })} /></label>{(['x', 'y'] as const).map(k => <label key={k}>{k.toUpperCase()}<input type="number" min="0" max={k === 'x' ? map.w - 1 : map.h - 1} value={row[k]} onChange={e => editRow({ [k]: Number(e.target.value) })} /></label>)}<button onClick={() => { edit(d => { const m = d.maps[mapId]; if (target.kind === 'npcs') m.npcs.splice(target.index, 1); else m.events.splice(target.index, 1) }); setTarget(undefined) }}>删除</button></div>
        {'trigger' in row && <><label>玩家看到的事件名称<input value={row.name ?? ''} onChange={e => editRow({ name: e.target.value || undefined })} /></label><div className="rpg-inline"><label>触发方式<select value={row.trigger} onChange={e => editRow({ trigger: e.target.value })}><option value="step">经过格子</option><option value="interact">靠近后主动交互</option></select></label><label><input type="checkbox" checked={!!row.once} onChange={e => editRow({ once: e.target.checked })} />仅触发一次</label></div><div className="rpg-inline">{(['flag', 'ifFlag', 'notFlag'] as const).map(k => <label key={k}>{({ flag: '完成开关', ifFlag: '需要开关', notFlag: '禁止开关' })[k]}<input value={row[k] ?? ''} onChange={e => editRow({ [k]: e.target.value || undefined })} /></label>)}</div></>}
        {!('trigger' in row) && <><label>绑定角色棋子与角色卡<select value={row.role ?? ''} onChange={e => editRow({ role: e.target.value || undefined })}><option value="">独立 NPC</option>{Object.entries(db.roles).map(([id, t]) => <option key={id} value={id}>{t.name}</option>)}</select></label><label>离场开关<input value={row.hideIfFlag ?? ''} onChange={e => editRow({ hideIfFlag: e.target.value || null })} /></label></>}
        <RpgScriptEditor db={db} value={row.script} onChange={script => editRow({ script })} />
      </section>}
      </>}
      {tab === 'data' && template && <section><h2>{template.name}</h2><label>名称<input value={template.name} onChange={e => edit(d => { d[category][dataId].name = e.target.value })} /></label><label>说明<textarea rows={4} value={String(template.desc ?? '')} onChange={e => edit(d => { d[category][dataId].desc = e.target.value })} /></label>{category !== 'items' && <div className="rpg-inline">{(['hp', 'ep', 'attack', 'defence', 'speed', 'iq'] as const).map(k => <label key={k}>{({ hp: '生命', ep: '能量', attack: '火力', defence: '装甲', speed: '机动', iq: '资质' })[k]}<input type="number" min="1" value={Number(template[k] ?? 1)} onChange={e => edit(d => { d[category][dataId][k] = Number(e.target.value) })} /></label>)}</div>}{category === 'items' && <div className="rpg-inline">{(['price', 'healHP'] as const).map(k => <label key={k}>{k === 'price' ? '售价' : '生命恢复量'}<input type="number" min="0" value={template[k] ?? 0} onChange={e => edit(d => { d[category][dataId][k] = Number(e.target.value) })} /></label>)}</div>}
        {category !== 'items' && <><h3>初始武功</h3><div className="rpg-trigger-list">{(Array.isArray(template.magics) ? template.magics : []).map((v, i) => { const id = typeof v === 'string' ? v : v.id; return <button key={id} onClick={() => edit(d => { d[category][dataId].magics = (d[category][dataId].magics as unknown[]).filter((_, n) => n !== i) })}>{(db.magics[id] as RpgMagic)?.name ?? id} ×</button> })}</div><select aria-label="添加初始武功" value="" onChange={e => { if (!e.target.value) return; const id = e.target.value; edit(d => { const row = d[category][dataId], all = Array.isArray(row.magics) ? row.magics : []; if (all.length >= 10) return; row.magics = [...all, id] }) }}><option value="">＋选择已定义的武功</option>{Object.entries(db.magics).filter(([id]) => !(Array.isArray(template.magics) ? template.magics : []).some(v => (typeof v === 'string' ? v : v.id) === id)).map(([id, v]) => <option key={id} value={id}>{(v as RpgMagic).name} · {SCHOOL_NAMES[(v as RpgMagic).school]}</option>)}</select></>}
        {category === 'items' && <><label>物品类型<select value={Number(template.type ?? 0)} onChange={e => edit(d => { d.items[dataId].type = Number(e.target.value) })}>{['剧情物品', '武器', '防具', '药品', '无人机', '秘籍 / 数据核心', '材料'].map((name, i) => <option key={name} value={i}>{name}</option>)}</select></label>{template.type === 5 && <><label>习得武功<select value={String(template.learn ?? '')} onChange={e => edit(d => { if (e.target.value) d.items[dataId].learn = e.target.value; else delete d.items[dataId].learn })}><option value="">只增加属性</option>{Object.entries(db.magics).map(([id, v]) => <option key={id} value={id}>{(v as RpgMagic).name}</option>)}</select></label><div className="rpg-inline">{(['needIQ', 'needExp'] as const).map(k => <label key={k}>{k === 'needIQ' ? '最低资质' : '基础修炼经验'}<input type="number" min="0" max="1000000" value={Number(template[k] ?? (k === 'needIQ' ? 0 : 1000))} onChange={e => edit(d => { d.items[dataId][k] = Number(e.target.value) })} /></label>)}</div></>}{(template.type === 1 || template.type === 2) && <div className="rpg-inline">{(['addAttack', 'addDefence', 'addSpeed', 'addMaxHP', 'addMaxEP'] as const).map(k => <label key={k}>{({ addAttack: '火力加成', addDefence: '装甲加成', addSpeed: '机动加成', addMaxHP: '生命加成', addMaxEP: '能量加成' })[k]}<input type="number" min="0" max="1000000" value={Number(template[k] ?? 0)} onChange={e => edit(d => { d.items[dataId][k] = Number(e.target.value) })} /></label>)}</div>}{template.type === 3 && <label>能量恢复量<input type="number" min="0" max="1000000" value={Number(template.healEP ?? 0)} onChange={e => edit(d => { d.items[dataId].healEP = Number(e.target.value) })} /></label>}</>}
        {category === 'roles' && <label>使用自定义棋子模板<select value="" onChange={e => { const entry = entries.find(v => v.id === e.target.value); if (entry) edit(d => { d.roles[dataId].tabletopAppearance = instantiateLibraryEntry(entry); d.roles[dataId].color = entry.template.color }) }}><option value="">{template.tabletopAppearance ? '已指定自定义棋子，选择可更换' : '从物件库选择棋子'}</option>{entries.filter(e => e.kind === 'figurine').map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
        <details><summary>完整条目数据</summary><p className="rpg-muted">保留RPG 的技能、装备、掉落等字段。武功、装备、修炼、成长与掉落在跑团规则中执行，战斗按武功配置投掷多颗实体骰子，整组落定后结算。</p><textarea className="rpg-json" rows={18} value={raw} onChange={e => setRaw(e.target.value)} /><button onClick={() => void run(() => { const v = JSON.parse(raw); if (!v || typeof v !== 'object' || Array.isArray(v) || typeof v.name !== 'string') throw new Error('条目需要名称和数据对象。'); edit(d => { d[category][dataId] = v }) })}>应用条目数据</button></details>
      </section>}
      {tab === 'skills' && <RpgSkillStudio db={db} entries={entries} onChange={edit} />}
      {tab === 'characters' && <RpgCharacterStudio definition={{ ...base, rpg: db }} entries={entries} onChange={next => { setBase(next); setDb(next.rpg!); setDirty(true) }} />}
      {tab === 'world' && <><section><h2>世界与作品</h2><label>作品简介<textarea rows={3} maxLength={4000} value={base.summary} onChange={e => { setBase(d => ({ ...d, summary: e.target.value })); setDirty(true) }} /></label><label>世界背景<textarea rows={5} value={base.world.premise} onChange={e => { setBase(d => ({ ...d, world: { ...d.world, premise: e.target.value } })); setDirty(true) }} /></label><p className="rpg-muted">剧情指令只能修改声明的数据。嵌套分支按顺序执行，对话、选择和遭遇暂停并等待玩家；存档会记住暂停的位置。</p><div className="rpg-inline"><button onClick={() => void run(() => { const fork = compiled(); fork.id = crypto.randomUUID(); fork.revision = 0; fork.title = `${fork.title.slice(0, 108)} · 副本`; setBase(fork); setDirty(true); setNotice('已复制为独立作品。保存后出现在游戏库。') })}>另存为独立作品</button><button onClick={() => void run(() => download(`${base.title}.rpg.json`, { v: 1, savedAt: new Date().toISOString(), db: validateRpgDatabase(db) }))}>导出 RPG 数据</button><button disabled={!previous} onClick={() => void run(() => { const draft = JSON.parse(previous!); const restored = adventureFromRpg(draft.db, draft.base); setBase(restored); setDb(restored.rpg!); setDirty(true); setMapId(restored.startSceneId.replace('rpg-map-', '')); setTarget(undefined); setNotice('已恢复进入工具前的缓存草稿。') })}>恢复缓存草稿</button></div></section><section><h3>玩法目标</h3><div className="rpg-inline"><label>收集目标名称<input value={db.settings?.objectiveName ?? '星核'} onChange={e => edit(d => { d.settings = { objectiveCount: 12, initialMoney: 300, ...d.settings, objectiveName: e.target.value } })} /></label><label>目标总数<input type="number" min="1" max="128" value={db.settings?.objectiveCount ?? 12} onChange={e => edit(d => { d.settings = { objectiveName: '星核', initialMoney: 300, ...d.settings, objectiveCount: Number(e.target.value) } })} /></label><label>初始货币<input type="number" min="0" max="1000000" value={db.settings?.initialMoney ?? 300} onChange={e => edit(d => { d.settings = { objectiveName: '星核', objectiveCount: 12, ...d.settings, initialMoney: Number(e.target.value) } })} /></label></div></section><section><h3>剧情文字演出</h3><label>文字样式<select aria-label="剧情文字样式" value={rpgTextEnabled({ title: base.title, rpg: db }) ? 'animated' : 'plain'} onChange={e => edit(d => { d.settings = { objectiveName: '星核', objectiveCount: 12, initialMoney: 300, ...d.settings, textStyle: e.target.value as 'animated' | 'plain' } })}><option value="animated">动态文字</option><option value="plain">简洁文字</option></select></label><p>为场景、抉择、招式、检定和关键奖励自动播放文字演出。完整对话始终保留，普通移动不会反复弹字。</p></section><section><h3>星图航线</h3>{db.world.locations.map((l, i) => <div className="rpg-inline" key={l.id}><b>{l.id}</b><label>地点名<input value={l.name} onChange={e => edit(d => { d.world.locations[i].name = e.target.value })} /></label><label>描述<input value={l.desc ?? ''} onChange={e => edit(d => { d.world.locations[i].desc = e.target.value })} /></label></div>)}</section></>}
    </main></div><input ref={input} hidden type="file" accept=".json,application/json" onChange={e => { void importFile(e.target.files?.[0]); e.target.value = '' }} />
  </div>
}
