import { useState } from 'react'
import type { RpgDatabase } from '../lib/rpg-schema'
import { AREA_NAMES, SCHOOL_NAMES, type RpgMagic } from '../lib/rpg-rules'
import { DicePoolEditor } from './DiceFields'
import type { LibraryEntry } from '../lib/object-library'

export default function RpgSkillStudio({ db, entries, onChange }: { db: RpgDatabase; entries?: LibraryEntry[]; onChange: (update: (draft: RpgDatabase) => void) => void }) {
  const [chosen, setChosen] = useState(''), [notice, setNotice] = useState('')
  const id = db.magics[chosen] ? chosen : Object.keys(db.magics)[0], magic = db.magics[id] as RpgMagic | undefined
  const patch = (v: Partial<RpgMagic>) => onChange(d => Object.assign(d.magics[id] as RpgMagic, v))
  function create() { const key = `skill_${crypto.randomUUID().slice(0, 8)}`; onChange(d => { d.magics[key] = { name: '自定义武功', desc: '', school: 0, ept: 2, area: 'point', dist: 1, power: 12, ep: 3 } }); setChosen(key); setNotice('新武功已创建。请在角色资料中配置初始武功，或通过秘籍的习得武功授予。') }
  function remove() {
    if ([...Object.values(db.roles), ...Object.values(db.enemies)].some(t => Array.isArray(t.magics) && t.magics.some(v => (typeof v === 'string' ? v : v?.id) === id)) || Object.values(db.items).some(i => i.learn === id)) { setNotice('有角色、敌人或秘籍引用此武功，请先移除引用。'); return }
    onChange(d => { delete d.magics[id] }); setChosen(''); setNotice('武功已删除。')
  }
  return <section><h2>武功与技能卡</h2><div className="rpg-inline"><select aria-label="选择编辑武功" value={id ?? ''} onChange={e => setChosen(e.target.value)}>{Object.entries(db.magics).map(([key, m]) => <option key={key} value={key}>{(m as RpgMagic).name} · {key}</option>)}</select><button onClick={create}>＋自定义武功</button>{magic && <button onClick={remove}>删除武功</button>}</div>{notice && <p role="status">{notice}</p>}{magic && <>
    <div className="rpg-skill-editor-grid"><label>名称<input value={magic.name} maxLength={120} onChange={e => patch({ name: e.target.value })} /></label><label>系别<select value={magic.school ?? 0} onChange={e => patch({ school: Number(e.target.value) })}>{SCHOOL_NAMES.map((name, i) => <option key={name} value={i}>{name}</option>)}</select></label><label>能量谱系<select value={magic.ept ?? 2} onChange={e => patch({ ept: Number(e.target.value) })}><option value={0}>暗物质</option><option value={1}>反物质</option><option value={2}>通用</option></select></label><label>范围形态<select value={magic.area} onChange={e => patch({ area: e.target.value as RpgMagic['area'] })}>{Object.entries(AREA_NAMES).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>{(['power', 'ep', 'dist'] as const).map(field => <label key={field}>{({ power: '基础威力', ep: '能量消耗', dist: '射程格数' })[field]}<input type="number" min={field === 'dist' ? 1 : 0} max={field === 'dist' ? 15 : 1e6} value={magic[field]} onChange={e => patch({ [field]: Number(e.target.value) })} /></label>)}<label>特殊效果<select value={magic.special ?? ''} onChange={e => patch({ special: e.target.value })}><option value="">普通</option><option value="stun">停滞</option><option value="stunAll">群体停滞</option><option value="double">连击</option><option value="pierce">穿透</option></select></label></div>
    <label>技能说明<textarea rows={3} value={magic.desc ?? ''} onChange={e => patch({ desc: e.target.value })} /></label><div className="rpg-inline">{([['heal', '治疗友军'], ['cure', '净化'], ['shield', '护盾'], ['suck', '吸取能量']] as const).map(([field, label]) => <label key={field}><span><input type="checkbox" checked={Boolean(magic[field])} onChange={e => patch({ [field]: e.target.checked })} />{label}</span></label>)}</div>
    <DicePoolEditor key={id} pool={magic.dicePool} school={magic.school} entries={entries} onChange={dicePool => onChange(d => { const m = d.magics[id] as RpgMagic; if (dicePool) m.dicePool = dicePool; else delete m.dicePool })} />
    <h3>十段成长</h3><p className="rpg-muted">每次使用增加1–2熟练度，每100点提高一段。可为每段分别指定威力、消耗、射程和范围。已有原作段位表会直接使用。</p>{magic.powLv ? <div style={{ overflowX: 'auto' }}><table className="rpg-skill-editor-levels"><thead><tr><th>段位</th><th>威力</th><th>能量</th><th>射程</th><th>范围</th></tr></thead><tbody>{Array.from({ length: 10 }, (_, i) => <tr key={i}><td>{i + 1}</td>{(['powLv', 'epLv', 'distLv'] as const).map(field => <td key={field}><input aria-label={`第${i + 1}段${field}`} type="number" min={field === 'distLv' ? 1 : 0} max={field === 'distLv' ? 15 : 1e6} value={magic[field]?.[i] ?? (field === 'powLv' ? magic.power : field === 'epLv' ? magic.ep : magic.dist)} onChange={e => { const row = [...magic[field] ?? Array(10).fill(field === 'powLv' ? magic.power : field === 'epLv' ? magic.ep : magic.dist)]; row[i] = Number(e.target.value); patch({ [field]: row }) }} /></td>)}<td><select value={magic.areaLv?.[i] ?? magic.area} onChange={e => { const row = [...magic.areaLv ?? Array(10).fill(magic.area)]; row[i] = e.target.value; patch({ areaLv: row }) }}>{Object.entries(AREA_NAMES).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></td></tr>)}</tbody></table></div> : <button onClick={() => patch({ powLv: [0.85, 1.05, 1.25, 1.45, 1.65, 1.9, 2.15, 2.4, 2.7, 3].map(f => Math.round(magic.power * f)), epLv: [1, 1.3, 1.6, 1.9, 2.2, 2.5, 2.9, 3.3, 3.7, 4.15].map(f => Math.round(magic.ep * f)), distLv: Array(10).fill(magic.dist), areaLv: Array(10).fill(magic.area) })}>生成十段成长表</button>}
    <p className="rpg-muted">角色和物品仍可使用自定义库外观；技能卡由这里的规则数据生成，游戏中的技能消耗、范围与效果会同步遵守配置。</p>
  </>}</section>
}
